# **The Power of NumPy**

In [4]:
range(0,5)

range(0, 5)

In [5]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [6]:
list(range(0,5,2))

[0, 2, 4]

In [7]:
list1 = [1,3,5,7,9]
list2 = [2,4,6,8,10]

In [8]:
list * list2

TypeError: can't multiply sequence by non-int of type 'type'

In [ ]:
new_list = []

for i in range(0,len(list1)):
    new_list.append(list1[i]*list2[i])

print(new_list)

In [ ]:
import numpy as np

np.multiply(list1,list2)

In [ ]:
x = np.array(list1)
y = np.array(list2)
x*y

In [ ]:
print(type(x))

# **NUMPY ARRAYS**

In [ ]:
np.array([2,4,6,8])

In [ ]:
variable = [5.8,9,7,5]

In [ ]:
print(type(variable[0]))
print(type(variable[1]))

In [ ]:
new_variable = np.array([5.8,9,7,5])

In [ ]:
new_variable.dtype

In [ ]:
new_variable

In [ ]:
new_variable2 = np.array([5.8,9,7,5], dtype = 'int')

In [ ]:
new_variable2

# **Creating NumPy Array with The Zeros() Function**

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3,5), dtype = 'int')

# **Creating NumPy Array with The Ones() Function**

In [ ]:
np.ones(10)

In [ ]:
np.ones((3,4,5), dtype = 'int')

# **Creating NumPy Array with The Full() Function**

In [10]:
np.full(8,5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [9]:
np.full((2,3),5, dtype = "float")

array([[5., 5., 5.],
       [5., 5., 5.]])

# Creating NumPy Array with The Arange() Function

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
eg = np.arange(4,11,dtype = 'float')

In [15]:
print(eg)

[ 4.  5.  6.  7.  8.  9. 10.]


In [16]:
type(eg)


numpy.ndarray

# Creating NumPy Array with The Eye() Function

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [20]:
np.eye(3,2,dtype = 'bool')

array([[ True, False],
       [False,  True],
       [False, False]])

# Creating NumPy Array with The Linspace() Function