# **The Power of NumPy**

In [1]:
range(0,5)

range(0, 5)

In [2]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,5,2))

[0, 2, 4]

In [4]:
list1 = [1,3,5,7,9]
list2 = [2,4,6,8,10]

In [5]:
list * list2

TypeError: can't multiply sequence by non-int of type 'type'

In [ ]:
new_list = []

for i in range(0,len(list1)):
    new_list.append(list1[i]*list2[i])

print(new_list)

In [7]:
import numpy as np

np.multiply(list1,list2)

array([ 2, 12, 30, 56, 90])

In [ ]:
x = np.array(list1)
y = np.array(list2)
x*y

In [ ]:
print(type(x))

# **NUMPY ARRAYS**

In [ ]:
np.array([2,4,6,8])

In [ ]:
variable = [5.8,9,7,5]

In [ ]:
print(type(variable[0]))
print(type(variable[1]))

In [ ]:
new_variable = np.array([5.8,9,7,5])

In [ ]:
new_variable.dtype

In [ ]:
new_variable

In [ ]:
new_variable2 = np.array([5.8,9,7,5], dtype = 'int')

In [ ]:
new_variable2

# **Creating NumPy Array with The Zeros() Function**

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3,5), dtype = 'int')

# **Creating NumPy Array with The Ones() Function**

In [ ]:
np.ones(10)

In [ ]:
np.ones((3,4,5), dtype = 'int')

# **Creating NumPy Array with The Full() Function**

In [ ]:
np.full(8,5)

In [ ]:
np.full((2,3),5, dtype = "float")

# Creating NumPy Array with The Arange() Function

In [ ]:
np.arange(5)

In [ ]:
eg = np.arange(4,11,dtype = 'float')

In [ ]:
print(eg)

In [ ]:
type(eg)


# Creating NumPy Array with The Eye() Function

In [ ]:
np.eye(3)

In [ ]:
np.eye(3,2)

In [ ]:
np.eye(3,2,dtype = 'bool')

# Creating NumPy Array with The Linspace() Function

In [8]:
np.linspace(5, 30, 10)


array([ 5.        ,  7.77777778, 10.55555556, 13.33333333, 16.11111111,
       18.88888889, 21.66666667, 24.44444444, 27.22222222, 30.        ])

# Creating NumPy Array with The Random() Function

In [9]:
# rand function
np.random.rand(2,4,9)

array([[[0.91329231, 0.22205779, 0.31939063, 0.46871339, 0.43266476,
         0.77467408, 0.52001052, 0.14544416, 0.71655322],
        [0.1734565 , 0.48970468, 0.97059801, 0.03619527, 0.63797655,
         0.16328799, 0.68429789, 0.77506181, 0.31132442],
        [0.08741103, 0.00840826, 0.677972  , 0.20051734, 0.63691112,
         0.66882276, 0.71122361, 0.21889532, 0.4831189 ],
        [0.03430403, 0.77519843, 0.58556859, 0.16097535, 0.81810368,
         0.85999876, 0.29012009, 0.45018189, 0.4863393 ]],

       [[0.18197775, 0.09077973, 0.79241661, 0.63119276, 0.30918393,
         0.67960733, 0.36147837, 0.57350728, 0.08829784],
        [0.02665444, 0.08436935, 0.97140143, 0.3187213 , 0.28381911,
         0.44337481, 0.3926445 , 0.5965068 , 0.85675666],
        [0.9964869 , 0.39749076, 0.96644449, 0.27302574, 0.23880855,
         0.1388396 , 0.70691433, 0.33949099, 0.75017752],
        [0.16284515, 0.79590704, 0.45480427, 0.84990186, 0.78589662,
         0.90751397, 0.33312985, 0.10542

In [10]:
# randn function
np.random.randn(6)

array([ 0.51082212, -0.62636687, -1.52001598,  0.85095451, -0.3125964 ,
        0.5681678 ])

In [11]:
# normal function
np.random.normal(20,5,(4,3))

array([[16.14430086, 21.09156141, 21.20669856],
       [13.50199493, 15.47321672, 17.92996324],
       [24.22576924, 20.39388972, 22.5495722 ],
       [28.4038976 , 24.50987692, 20.37367537]])

In [16]:
# randint function
np.random.randint(0,10,(4,4))

array([[7, 4, 4, 4],
       [6, 9, 4, 6],
       [5, 0, 1, 4],
       [6, 6, 6, 9]])

# Properties of NumPy Array

In [17]:
matrix = np.random.randint(10,50,(5,4))

In [18]:
matrix

array([[34, 43, 34, 10],
       [20, 48, 21, 14],
       [39, 29, 21, 16],
       [17, 26, 24, 33],
       [11, 30, 43, 13]])

In [19]:
matrix.shape

(5, 4)

In [20]:
matrix.ndim

2

In [21]:
matrix.size

20

In [22]:
matrix.dtype

dtype('int32')

# Reshaping a NumPy Array: Reshape() Function

In [25]:
example = np.arange(1,16)
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
example.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
array = example.reshape(1,15)
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [30]:
array.ndim

2

In [29]:
example.ndim

1

In [31]:
example.reshape((4,3))

ValueError: cannot reshape array of size 15 into shape (4,3)

In [32]:
example.reshape((4,4))

ValueError: cannot reshape array of size 15 into shape (4,4)

# Largest Element of a Numpy Array: Max(), Argmax() Functions

In [34]:
array1 = np.random.randint(0,50,10)
array1

array([20, 36, 48, 37,  8, 44, 24, 41, 38,  0])

In [37]:
array1.max()

48

In [38]:
array1.argmax()

2

In [39]:
array2 = np.random.randint(0,50,(4,3))
array2

array([[12, 47, 47],
       [17, 36, 34],
       [46, 26, 25],
       [ 6, 23, 11]])

In [40]:
array2.max()

47

In [41]:
array2.argmax()

1

# Least Element of Numpy Array: Min(), Argmin() Functions

In [43]:
array3 = np.random.randint(20, 70, 10)
array3

array([54, 43, 36, 40, 26, 22, 56, 49, 69, 48])

In [44]:
array3.min()

22

In [45]:
array3.argmin()

5

In [46]:
array4 = np.random.randint(20, 70, (5,3))
array4

array([[35, 63, 55],
       [63, 65, 69],
       [34, 55, 44],
       [36, 43, 55],
       [34, 43, 65]])

In [48]:
array4.min()

34

In [47]:
array4.argmin()

6

# Concatenating Numpy Arrays